name: HPDueling
version: 0.1
author: KmanCrazy
main: me.KmanCrazy.dueling.Main
commands:
   dueling:
     description: Duel with a friend or an enemy or a group!
   options:
     description: Set the options of an arena!