name: Dueling
version: ${project.version}
author: KmanCrazy
main: me.KmanCrazy.dueling.DuelingPlugin
commands:
   dueling:
     description: Duel with a friend or an enemy or a group
   options:
     description: Set the options of an arena